import typing

from . import ast

def serialize(nodes: typing.Iterable[ast.Node]) -> str: ...
def serialize_identifier(value: str) -> str: ...
def serialize_name(value: str) -> str: ...
def serialize_string_value(value: str) -> str: ...
def serialize_url(value: str) -> str: ...

BAD_PAIRS: typing.Set[typing.Tuple[str, str]]
