from typing import Dict, Pattern

class EntitySubstitution:
    CHARACTER_TO_HTML_ENTITY: Dict[str, str] = ...
    HTML_ENTITY_TO_CHARACTER: Dict[str, str] = ...
    CHARACTER_TO_HTML_ENTITY_RE: Pattern[str] = ...
    CHARACTER_TO_XML_ENTITY: Dict[str, str] = ...
    BARE_AMPERSAND_OR_BRACKET: Pattern[str] = ...
    AMPERSAND_OR_BRACKET: Pattern[str] = ...
    @classmethod
    def quoted_attribute_value(self, value: str) -> str: ...
    @classmethod
    def substitute_xml(cls, value: str, make_quoted_attribute: bool = ...) -> str: ...
    @classmethod
    def substitute_xml_containing_entities(cls, value: str, make_quoted_attribute: bool = ...) -> str: ...
    @classmethod
    def substitute_html(cls, s: str) -> str: ...
