from bs4.dammit import EntitySubstitution
from typing import Any, Optional, Dict, Set, Callable

class Formatter(EntitySubstitution):
    XML_FORMATTERS: Dict[Any, Any] = ...
    HTML_FORMATTERS: Dict[Any, Any] = ...
    HTML: str = ...
    XML: str = ...
    HTML_DEFAULTS: Dict[str, Set[str]] = ...
    language: Optional[str] = ...
    entity_substitution: Optional[Callable[[str], str]] = ...
    void_element_close_prefix: str = ...
    cdata_containing_tags: Set[str] = ...
    def __init__(self,
                 language: Optional[str] = ...,
                 entity_substitution: Optional[Callable[[str], str]] = ...,
                 void_element_close_prefix: str = ...,
                 cdata_containing_tags: Optional[Set[str]] = ...,
    ) -> None: ...
    def substitute(self, ns: str) -> str: ...
    def attribute_value(self, value: str) -> str: ...
    def attributes(self, tag: Any) -> Any: ...
