name: "Quality Assurance"
on: [push]
jobs:
  "Lint":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: make dev_requirements.txt.stamp
      - run: make lint
      - run: make format
      - name: "Dirty check"
        run: |
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            PAGER= git diff --cached
            exit 1
          fi
